# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events on every branch
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        # Select platform(s)
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        # Select compatible Smalltalk image(s)
        smalltalk: [ Squeak64-trunk, Squeak64-5.3, Squeak64-5.2, Squeak64-5.1 ]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@1.1.0
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Test ChangesBrowser
        run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
        env:
          COVERALLS_PARALLEL: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  finish:
    name: Notify Coveralls
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Coveralls that parallel builds have finished
        run: curl https://coveralls.io/webhook?repo_token=${{ secrets.COVERALLS_REPO_TOKEN }} -d "payload[build_num]=${{ github.run_id }}&payload[status]=done"
